### ISSUE TITLE
Typing :!!a panics

### ISSUE THREAD

**Issue by steffahn** [Canop/broot#326]
Or typing just about anything containing a `!` thatʼs not the first or the last letter after `:`.
### Backtrace
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/frank/.cargo/registry/src/github.com-1ecc6299db9ec823/broot-1.2.0/src/verb/verb_invocation.rs:81:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
   3: <broot::verb::verb_invocation::VerbInvocation as core::convert::From<&str>>::from
   4: broot::command::parts::CommandParts::from
   5: broot::command::panel_input::PanelInput::on_event
   6: broot::app::app::App::run
   7: broot::cli::run
   8: broot::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
<details><summary><b><i>full backtrace</i></b></summary>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/frank/.cargo/registry/src/github.com-1ecc6299db9ec823/broot-1.2.0/src/verb/verb_invocation.rs:81:10
stack backtrace:
   0:     0x55d38df21b80 - std::backtrace_rs::backtrace::libunwind::trace::h04d12fdcddff82aa
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x55d38df21b80 - std::backtrace_rs::backtrace::trace_unsynchronized::h1459b974b6fbe5e1
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d38df21b80 - std::sys_common::backtrace::_print_fmt::h9b8396a669123d95
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d38df21b80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he009dcaaa75eed60
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d38de2a93c - core::fmt::write::h77b4746b0dea1dd3
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
   5:     0x55d38df21471 - std::io::Write::write_fmt::heb7e50902e98831c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
   6:     0x55d38df20e25 - std::sys_common::backtrace::_print::h2d880c9e69a21be9
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d38df20e25 - std::sys_common::backtrace::print::h5f02b1bb49f36879
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d38df20e25 - std::panicking::default_hook::{{closure}}::h658e288a7a809b29
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
   9:     0x55d38df203ed - std::panicking::default_hook::hb52d73f0da9a4bb8
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
  10:     0x55d38df203ed - std::panicking::rust_panic_with_hook::hfe7e1c684e3e6462
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
  11:     0x55d38df3d54e - std::panicking::begin_panic_handler::{{closure}}::h42939e004b32765c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:497:13
  12:     0x55d38df3d4ec - std::sys_common::backtrace::__rust_end_short_backtrace::h9d2070f7bf9fd56c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55d38df3d49d - rust_begin_unwind
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
  14:     0x55d38de280f0 - core::panicking::panic_fmt::ha0bb065d9a260792
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
  15:     0x55d38de27f0c - core::panicking::panic::h339b30ca166fd852
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
  16:     0x55d38dc96303 - <broot::verb::verb_invocation::VerbInvocation as core::convert::From<&str>>::from::hf882a7496ab6895b
  17:     0x55d38dc9554e - broot::command::parts::CommandParts::from::h34f007bd9e607a88
  18:     0x55d38dd5183a - broot::command::panel_input::PanelInput::on_event::h04f913d006d79652
  19:     0x55d38dd4a7f4 - broot::app::app::App::run::hdbf5e9e538920af1
  20:     0x55d38dd8a294 - broot::cli::run::hf37f440fbf0f380d
  21:     0x55d38dc15ed5 - broot::main::h51e571f598cc8c03
  22:     0x55d38dc138c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h220a81c063e59f7e
  23:     0x55d38dc16ac5 - main
  24:     0x7fc83c333cb2 - __libc_start_main
  25:     0x55d38dc137fe - _start
  26:                0x0 - <unknown>
```

</details>

<details><summary><b><i>broot.log</i></b></summary>

```
21:45:13.611 [INFO] cli_log: Starting broot v0.1.0 with log level DEBUG
21:45:13.611 [DEBUG] broot::cli: read conf took 111.38µs
21:45:13.611 [DEBUG] broot::cli: config: Conf {
    files: [
        "/home/frank/.config/broot/conf.hjson",
    ],
    default_flags: None,
    date_time_format: None,
    verbs: [
        VerbConf {
            invocation: Some(
                "edit",
            ),
            internal: None,
            external: None,
            execution: Some(
                String(
                    "$EDITOR +{line} {file}",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: Some(
                "F2",
            ),
            shortcut: Some(
                "e",
            ),
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: Some(
                "create {subpath}",
            ),
            internal: None,
            external: None,
            execution: Some(
                String(
                    "$EDITOR {directory}/{subpath}",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: None,
            shortcut: None,
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: Some(
                "git_diff",
            ),
            internal: None,
            external: None,
            execution: Some(
                String(
                    "git difftool -y {file}",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: None,
            shortcut: Some(
                "gd",
            ),
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: Some(
                "terminal",
            ),
            internal: None,
            external: None,
            execution: Some(
                String(
                    "$SHELL",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: Some(
                "ctrl-t",
            ),
            shortcut: None,
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: Some(
                true,
            ),
            description: None,
        },
        VerbConf {
            invocation: Some(
                "dragon",
            ),
            internal: None,
            external: Some(
                Array(
                    [
                        "sh",
                        "-c",
                        "dragon -x -T {file} &",
                    ],
                ),
            ),
            execution: None,
            cmd: None,
            cmd_separator: None,
            key: None,
            shortcut: None,
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: Some(
                "cargo_clean",
            ),
            internal: None,
            external: Some(
                Array(
                    [
                        "sh",
                        "-c",
                        "cd {directory}; cargo clean",
                    ],
                ),
            ),
            execution: None,
            cmd: None,
            cmd_separator: None,
            key: None,
            shortcut: Some(
                "cc",
            ),
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: Some(
                "exit_shell",
            ),
            internal: None,
            external: Some(
                String(
                    "exit",
                ),
            ),
            execution: None,
            cmd: None,
            cmd_separator: None,
            key: None,
            shortcut: None,
            leave_broot: None,
            from_shell: Some(
                true,
            ),
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
    ],
    skin: None,
    special_paths: {},
    search_modes: None,
    disable_mouse_capture: None,
    cols_order: None,
    show_selection_mark: None,
    ext_colors: {},
    syntax_theme: None,
    true_colors: None,
    icon_theme: None,
    modal: None,
}
21:45:13.615 [DEBUG] broot::app::context: COLORTERM env variable = "truecolor"
21:45:13.615 [DEBUG] broot::app::context: true colors are available
21:45:13.615 [DEBUG] broot::tree_build::builder: GitIgnorer::default took 71ns
21:45:13.620 [DEBUG] broot::app::app: display panel took 399.648µs
21:45:13.621 [DEBUG] broot::app::app: pending_tasks took 383ns
21:45:15.814 [INFO] broot::app::app: event: Key(KeyEvent { code: Char(':'), modifiers: NONE })
21:45:15.814 [DEBUG] broot::app::app: command after add_event: VerbEdit(VerbInvocation { name: "", args: None, bang: false })
21:45:15.814 [DEBUG] broot::app::panel: result in panel PanelId(0): Ok(Keep)
21:45:15.814 [DEBUG] broot::app::app: display panel took 488.242µs
21:45:15.814 [DEBUG] broot::app::app: pending_tasks took 817ns
21:45:15.933 [INFO] broot::app::app: event: Key(KeyEvent { code: Char('!'), modifiers: NONE })
21:45:15.934 [DEBUG] broot::app::app: command after add_event: VerbEdit(VerbInvocation { name: "", args: None, bang: true })
21:45:15.934 [DEBUG] broot::app::panel: result in panel PanelId(0): Ok(Keep)
21:45:15.934 [DEBUG] broot::app::app: display panel took 445.381µs
21:45:15.934 [DEBUG] broot::app::app: pending_tasks took 410ns
21:45:16.118 [INFO] broot::app::app: event: Key(KeyEvent { code: Char('!'), modifiers: NONE })
21:45:16.118 [DEBUG] broot::app::app: command after add_event: VerbEdit(VerbInvocation { name: "", args: None, bang: true })
21:45:16.118 [DEBUG] broot::app::panel: result in panel PanelId(0): Ok(Keep)
21:45:16.119 [DEBUG] broot::app::app: display panel took 354.051µs
21:45:16.119 [DEBUG] broot::app::app: pending_tasks took 628ns
21:45:16.302 [INFO] broot::app::app: event: Key(KeyEvent { code: Char('a'), modifiers: NONE })
```

</details>

## Configuration
- broot version: 1.2.0 (installed via `cargo install`)
- OS: Ubuntu 20.10

**Comment by Canop** [comment]
Confirmed, thanks

**Comment by Canop** [comment]
Interesting. I'm fixing the crash but there's still a kind of "hole" in broot syntax.

When you type `:a!b`, the `b` has no meaning for broot.

More generally, there's no meaning in broot for any character between the optional bang following a verb and the first space or colon (or end of input).

Right now I'll just ignore it but this behavior may change in the future.

**Comment by Canop** [comment]
There's no more "hole" in the verb invocation syntax. Now, the verb arguments can immediately follow the optional post bang.
