### ISSUE TITLE
broot panics without a user-friendly error message if BROOT_LOG is set but log file is unwritable

### ISSUE THREAD

**Issue by acuteaangle** [Canop/broot#951]
## Description 
In trying to find a minimal example of https://github.com/Canop/broot/issues/807, I encountered a panic while running `BROOT_LOG=debug broot` in an unwritable directory.

## Tested Versions
1. broot 1.44.0 from nixpkgs, on x86_64
2. broot 1.38.0 from nixpkgs, on aarch64
3. broot 1.38.0 from nixpkgs, on x86_64

broot is unable to run on NixOS without patching, so I was not currently able to test it from from git

## Tested Filesystems
- btrfs
- tmpfs

## System Information
1. - Kernel: 6.9.2-hardened1
   - Distro: NixOS 24.05 (Uakari)
   - arch: x86_64
2. - Kernel: 6.6.32
   - Distro: NixOS 24.05 (Uakari) 
   - arch: aarch64
3. - Kernel: 6.6.52
   - Distro: NixOS 24.11 (Vicuna)
   - arch: x86_64

## Minimal Reproduction
```console
$ cd $(mktemp -d)

$ chmod -w .

$ BROOT_LOG=debug broot                                                                              
thread 'main' panicked at /build/broot-1.38.0-vendor.tar.gz/cli-log/src/init.rs:30:14:                                              
Log file can't be created: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }                                    
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                       
                                                                                                                                    
$ BROOT_LOG=debug RUST_BACKTRACE=1 broot                                                             
thread 'main' panicked at /build/broot-1.38.0-vendor.tar.gz/cli-log/src/init.rs:30:14:                                              
Log file can't be created: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }                                    
stack backtrace:                                                                                                                    
   0: rust_begin_unwind                                                                                                             
   1: core::panicking::panic_fmt                                                                                                    
   2: core::result::unwrap_failed                                                                                                   
   3: broot::main                                                                                                                   
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.                                             

$ BROOT_LOG=debug RUST_BACKTRACE=full broot                                                          
thread 'main' panicked at /build/broot-1.38.0-vendor.tar.gz/cli-log/src/init.rs:30:14: 
Log file can't be created: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
stack backtrace:
   0:        0x1dc7afb59 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4886110ae7835fd2
   1:        0x1dc5af160 - core::fmt::write::h6fab83f0f5bc0c8f
   2:        0x1dc7c5a2d - std::io::Write::write_fmt::h64824cb874054607
   3:        0x1dc7b078e - std::sys_common::backtrace::print::hb8fea9d041077138
   4:        0x1dc7b0360 - std::panicking::default_hook::{{closure}}::hc60f0f690c67943c
   5:        0x1dc7b1008 - std::panicking::rust_panic_with_hook::hd61e30fe5971d187
   6:        0x1dc7b0a20 - std::panicking::begin_panic_handler::{{closure}}::h95d2684e28f89fd2
   7:        0x1dc7b0976 - std::sys_common::backtrace::__rust_end_short_backtrace::h48780d898316fff8
   8:        0x1dc7b0963 - rust_begin_unwind
   9:        0x1dc2a9364 - core::panicking::panic_fmt::hdb89b5c14a056cec
  10:        0x1dc2a9322 - core::result::unwrap_failed::h850510ea6c159887
  11:        0x1dc2cdac3 - broot::main::h2e20cf9c38dcd09a
  12:        0x1dc2c1ee3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc9fdd8d1a2e6e1af
  13:        0x1dc2ce27d - main
  14:     0x63745565510e - __libc_start_call_main
  15:     0x6374556551c9 - __libc_start_main@@GLIBC_2.34
  16:        0x1dc2c1e15 - _start
  17:                0x0 - <unknown>
```

**Comment by Canop** [comment]
Thanks for the clear report

**Comment by Canop** [comment]
> In trying to find a minimal example of https://github.com/Canop/broot/issues/807

That would be appreciated
